name: graphchain-local-env
channels:
  - defaults
  - conda-forge
dependencies:
  - autopep8
  - cloudpickle
  - dask
  - fs-s3fs
  - isort
  - joblib
  - jupyterlab
  - m2r
  - mypy
  - pydocstyle
  - pytest
  - pytest-cov
  - pytest-xdist
  - sphinx
  - sphinx_rtd_theme
  - twine
  - pip:
      - flake8
      - flake8-comprehensions
      - flake8-bandit
      - flake8-bugbear
      - flake8-mutable
      - flake8-rst-docstrings
      - lz4
