name: graphchain-circleci-env
channels:
  - defaults
  - conda-forge
dependencies:
  - cloudpickle=0.6
  - dask=0.19
  - flake8=3.5
  - flake8-comprehensions=1.4
  - fs-s3fs=0.1
  - joblib=0.12
  - mypy<0.700
  - pydocstyle=2.1
  - pytest=3.8
  - pytest-cov=2.6
  - pytest-xdist=1.23
  - pip:
      - flake8-bugbear~=18.8.0
      - lz4~=2.1.0
