name: graphchain-circleci-env
channels:
  - defaults
  - conda-forge
dependencies:
  - cloudpickle=0.6
  - dask=1.0
  - fs-s3fs=0.1
  - joblib=0.13
  - mypy<0.700
  - pydocstyle=3.0
  - pytest=4.0
  - pytest-cov=2.6
  - pytest-xdist=1.25
  - pip:
      - flake8~=3.6.0
      - flake8-comprehensions~=1.4.1
      - flake8-bandit~=2.0.0
      - flake8-bugbear~=18.8.0
      - flake8-mutable~=1.2.0
      - flake8-rst-docstrings~=0.0.8
      - lz4~=2.1.6
